### ISSUE TITLE
[Training][Hoa] Tiến độ sản phẩm

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#17]
- Học sản phẩm: 150/178

Mục tiêu: đến 8/4/2017 - 178 sản phẩm

**Comment by phanhoa155** [comment]
Ngày 21/3: 60/178 sản phẩm

**Comment by phanhoa155** [comment]
Ngày 21/3: 80/178 sản phẩm
Ngày 23/3: 87/178 sp
Ngày 24/3: 100/178 sp
