### ISSUE TITLE
[Event] 5 năm thành lập công ty

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#19]
Kỉ niệm thành lập công ty 6/4/2017
Ngày tổ chức: thứ 4, 5/4/2017 (do 6/4/2017 trùng ngày thành lập công ty và giỗ tổ Vua Hùng)

Trò chơi:
- Đoán sản phẩm: DONE
Chi tiết:
https://github.com/phatls/CallCenter_Customer/issues/19#issuecomment-287965391

- Hình đoán chữ: DONE
Chi tiết:
https://github.com/phatls/CallCenter_Customer/issues/19#issuecomment-287954055

- Công dụng sản phẩm: DONE
Chi tiết:
[Sản phẩm.xlsx](https://github.com/phatls/CallCenter_Customer/files/857051/S.n.ph.m.xlsx)

Quản trò: Lâm

**Comment by phanhoa155** [comment]
Hình đoán chữ: 10/10
[Hinh doan chu.pptx](https://github.com/phatls/CallCenter_Customer/files/857014/Hinh.doan.chu.pptx)

**Comment by phatls** [comment]
Đoán sản phẩm: 10/10
[Đoán sản phẩm.pptx](https://github.com/phatls/CallCenter_Customer/files/857041/Doan.s.n.ph.m.pptx)
