### ISSUE TITLE
[Cancel][LA][Sinh Nhớ] Khách hàng thông báo Bulong mắc

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#2]
Ngày 6/3/2017 khách hàng báo sản phẩm Bulong gia mắc và trả hàng

**Comment by phatls** [comment]
Đã thông báo khách hàng và giảm giá ko nhận hàng gửi lại

**Comment by phatls** [comment]
Đã thông báo khách hàng và giảm giá ko nhận hàng gửi lại

**Comment by phanhoa155** [comment]
nhận hàng lại không giảm giá

**Comment by phatls** [comment]
okie, đóng lại giúp
