### ISSUE TITLE
[Tây Ninh][Đắc Thi] Thiếu hàng

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#26]
Thiếu cọ lăn 1 tấc
Giải quyết: Thông báo khách hàng là hết hàng, khi nào có hàng sẽ báo lại cho KH

**Comment by phatls** [comment]
Vớt hàng lại cho khách hàng khi có toa sau (nhưng vẫn tính hóa đơn bình thường)

**Comment by phatls** [comment]
Done
