### ISSUE TITLE
[Doanh thu] Cách thức báo cáo doanh thu cho bộ phận CSKH

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#29]
Tăng doanh thu
- Lấy số đthoại từ Gmin
- Hỏi thông tin từ a Cầu
- Xem hàng rớt
- Hỏi thông tin zalo để nhận đơn hàng

**Comment by phanhoa155** [comment]
Vấn đề: Báo cáo doanh thu của một nhân viên 
Giải pháp:
 - Hỏi cách báo cáo Doanh thu từ Trinh.Nn
- Nhờ Vi.Tma xuất doanh thu tuyến VT
- Hoa.Pa xem Hóa đơn ghi sổ rồi tự mình đánh dấu

**Comment by phanhoa155** [comment]
Giải quyết:
Vào Flamigo---> Bán hàng và Marketing----> Doanh số----> Filter theo tuyến VT----> Chọn ngày---> Show all----> Xuất ra Excel và tính tổng

**Comment by phatls** [comment]
Dựa phiếu giao hàng từ kế toán bán hàng ==> Ghi nhận người nhận và Sale theo mẫu để chốt doanh thu
[BCGHVT_20170414.xlsx](https://github.com/phatls/CallCenter_Customer/files/923248/BCGHVT_20170414.xlsx)
