### ISSUE TITLE
[Sai ngày xuất hàng] Ngày xuất chuyển tháng bị sai

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#33]
Ví dụ: Hôm nay ngày 31/3/2017

1. Tạo đơn hàng 
2. Tìm và chọn một KH
3. Màng hình tự động chuyển tới ngày xuất hàng

Kết quả mong đợi: Ngày xuất hàng : 2/4/2017

Kết quả thực tế: Ngày xuất hàng: 4/2/2017

**Comment by phatls** [comment]
DONE
