### ISSUE TITLE
[VT][Sáng Em VT][Giao hàng chậm] 

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#34]
Ngày 3/4: KH phản ánh giao hàng chậm 10 ngày

**Comment by phatls** [comment]
Tìm chành thay thế, chứ không phụ thuộc vào 1 chành cố định:
1. Liên hệ cửa hàng xác nhận có chành khác và cách thức thanh toán (ưu tiên có thu hộ hoặc khách hàng chuyển khoản được)
2. Nếu 1 trả lời có, thì liên hệ chành gửi hiện tại, nhận hàng lại và chuyển chành mới. Công ty có thể hỗ trợ phí chuyển trong trường hợp chậm này.
