### ISSUE TITLE
[Báo giá] Báo giá cho cửa hàng mới

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#35]
1.Họ tên: Anh Nhựt, sđt: 0946931093
gmail: huynhut82@gmail.com, ko dùng zalo
Thị trấn Tân Hưng, huyện Tân hưng , tỉnh Long An
2. KH mở cửa hàng đầu tư khoảng : 100trieu
3. Tất cả sản phẩm đồ sắt. Đặc biệt dùng cho Công trình xây dựng
4. Họ cần đưa ra tất cả sản phẩm của mình để họ đánh dấu vào những sp họ cần lấy. Sau đó mình báo giá những san pham đó

**Comment by phatls** [comment]
Từ các biểu hiện trên, vấn đề khách hàng: 
Cung cấp danh sách sản phẩm, đặc biệt công trình xây dựng

Giải pháp:
1. Gửi danh sách BGBH hiện có
2. Lọc 2 bảng: Dụng cụ xây dựng và nhóm khác: 

[Danh sach dung cu xay dung.xlsx](https://github.com/phatls/CallCenter_Customer/files/908009/Danh.sach.dung.cu.xay.dung.xlsx)
[Danh sach san pham khac.xlsx](https://github.com/phatls/CallCenter_Customer/files/908010/Danh.sach.san.pham.khac.xlsx)


3. Sau khi, khách hàng chọn sản phẩm => Mình báo giá

(Vì bản chất công ty bv gom hàng giùm, khó có bảng giá chốt, nên chỉ báo giá theo đơn hàng)

**Comment by phanhoa155** [comment]
Mail: 
Thân gửi anh Nhựt,
Em là Phan Thị Ánh Hoa- SDT: 0902995247- Zalo: 0902995247, nhân viên Bộ phận chăm sóc khách hàng của Công Ty Cổ Phần Thương Mại Bách Việt. 
Như  đã trao đổi với anh vào hôm thứ bảy ngày 8/4/2017, bên em sẽ gửi danh sách các sản phẩm của công ty em cho anh xem và đánh dấu vào các sản phẩm anh cần.
Nhằm đáp ứng được thỏa thuận của công ty em và anh nhanh, hiệu quả hôm nay em gửi a 2 file: Danh sách dụng cụ xây dựng, Danh sách sản phẩm khác. Một file chuyên về dụng cụ xây dựng anh cần, và một file là các sản phẩm công ty em có để a tham khảo thêm.
Mong a xem và phản hồi giúp bên em sớm để tiến độ công việc được thực hiện nhanh chóng!
Em xin chân thành cảm ơn a!
Hoa
[Danh sach dung cu xay dung.xlsx](https://github.com/phatls/CallCenter_Customer/files/908028/Danh.sach.dung.cu.xay.dung.xlsx)
[Danh sach san pham khac.xlsx](https://github.com/phatls/CallCenter_Customer/files/908029/Danh.sach.san.pham.khac.xlsx)

**Comment by phatls** [comment]
Góp ý sửa email của Hoa:
Thân gửi anh Nhựt,
Em là Phan Thị Ánh Hoa- SDT: 0902995247- Zalo: 0902995247, nhân viên Bộ phận chăm sóc khách hàng của Công Ty Cổ Phần Dịch Vụ Thương Mại Thiết bị Bách Việt.
Trước tiên, cảm ơn về chuyến thăm công ty vừa qua.
Sau đến, em xin gửi anh 1 số thông tin xác nhận sau cuộc gặp như sau:
1. Khách hàng: Anh Nhựt, SĐT: 0946931093
Gmail: huynhut82@gmail.com
Zalo: Không
Địa chỉ: Thị trấn Tân Hưng, huyện Tân hưng , tỉnh Long An
2. Mức độ đầu tư cửa hàng: 100 triệu
3. Sản phẩm: Tất cả sản phẩm đồ sắt. Đặc biệt dùng cho Công trình xây dựng
4. Yêu cầu từ khách hàng: 
- Cung cấp tất cả sản phẩm của công ty Bách Việt
- Báo giá những sản phẩm sau khi khách hàng chọn sản phẩm

Vì vậy, hôm nay, em gửi mail này để gửi đến anh thông tin sản phẩm của công ty Bách Việt gồm 2 phần:
- Danh sách sản phẩm dụng cụ xây dựng
- Danh sách sản phẩm khác

Mong anh xem xét và phản hồi sớm giúp công ty về những sản phẩm anh quan tâm. Sau đó, em sẽ gửi báo giá sớm nhất cho anh.
Em xin chân thành cảm ơn a!
Hoa

**Comment by phatls** [comment]
Sau khi gửi mail, nhớ gọi điện báo khách hàng check mail. 1~2 ngày phải hỏi thăm lại và xác nhận cuộc gọi lần kế tiếp.

**Comment by phanhoa155** [comment]
13/4 gọi lại KH

**Comment by phanhoa155** [comment]
Đợi A. Nhựt xem xong và gọi lại (15~16/4)

**Comment by phanhoa155** [comment]
Khách hàng thông báo dời thời gian mở cửa hàng
