### ISSUE TITLE
[Phân tuyến] Vũng Tàu

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#36]
Phân tuyến khách hàng Vũng Tàu:
Giải quyết:
- KH điện đặt hàng---> Hỏi Chành A. Cường có giao được ngày đó ko?
- Nếu A.C trả lời được đồng ý với KH 2 ngày sau hàng sẽ về chành tại Vũng Tàu. Nếu ko được hỏi KH có cần giao chành xe khác để nhanh ko. Ghi lại tên chành xe, số điện thoại để gửi hàng cho KH.

**Comment by phanhoa155** [comment]
[tuyen Vt (2).xlsx](https://github.com/phatls/CallCenter_Customer/files/946419/tuyen.Vt.2.xlsx)
