### ISSUE TITLE
[Rớt hàng] Xử lý khi hóa đơn có tính tiền, nhưng thực thế không có hàng

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#38]
Biểu hiện rớt hàng:
- Hóa đơn có tính tiền, nhưng thực tế không có hàng: Ví dụ: Đơn hàng cửa hàng Duy VT ngày 9/3/2017
- Khách hàng có đặt hàng, nhưng hóa đơn và thực tế không có hàng: Ví dụ: Hàng ngày nhiều đơn hàng bị vài món
- Sản phẩm công ty hoàn toàn ko bán

Nêu vấn đề, giải pháp cho biểu hiện trên?

**Comment by phanhoa155** [comment]
#42
#43
