### ISSUE TITLE
[Trả hàng] Quy trình theo dõi trả hàng từ chỗ khách hàng đến khi nhận

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#40]
Vấn đề: Chưa theo được hàng trả
Giải pháp:
1. Có trả hàng thì phải kí nhận trả hàng trên hóa đơn có 2 chữ kí
2. Làm phiếu trả hàng riêng theo dõi riêng

Thảo luận để chốt cách phối hợp

**Comment by phanhoa155** [comment]
#42
#43

**Comment by phanhoa155** [comment]
Đã thông báo để chị Vy làm
