### ISSUE TITLE
[Trả hàng] [Phước Toàn] Xác nhận hàng trả đang ở đâu

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#41]
Xác nhận với các bên biết tình trạng hàng trả đang ở đâu?

- Vy báo: 4/4 có trả 4 cây kềm century ở toa ngày 30/3 nhưng ko thấy hàng trả đâu

**Comment by phanhoa155** [comment]
Nhờ a Minh chốt với a Cường Hàng ko có giờ a muốn xử lý ra sao? Ngày 14/4 Hoa sẽ xác nhận lại với a Minh tình trạng

**Comment by phanhoa155** [comment]
Hàng đã được a Cường trả lên
