### ISSUE TITLE
[Thiếu hàng][CH Mai VT] Thiếu hàng

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#42]
Ngày 4/4: Thiếu 1 kiện bánh xe vàng
Tình trạng: Xót lại trên xe a Cường 
Giải quyết: Điện a Cường hỏi hàng
Ngày 11/4: Thiếu 2 thùng sơn xịt ATM
Tình trạng: Ko có hàng mà chị V tính tiền
Giải quyết: Bù hàng mà ko tính tiền cho toa sau

**Comment by phatls** [comment]
Vớt hàng lại cho khách hàng khi có toa sau (nhưng vẫn tính hóa đơn bình thường)

**Comment by phanhoa155** [comment]
Đã bù hàng
