### ISSUE TITLE
[Vũng Tàu][Việt Tú] Giao thiếu hàng trên hoá đơn của khách hàng

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#52]
Giao thiếu hàng trên hoá đơn của khách hàng

Giải pháp:
1. Thương lượng khách hàng tính tiền trừ hàng thiếu ra
=> Khách hàng không đồng ý
2. Thương lượng bù hàng sau đó ra thu tiền

**Comment by phanhoa155** [comment]
[Viet tu.xlsx](https://github.com/phatls/CallCenter_Customer/files/933171/Viet.tu.xlsx)

**Comment by phatls** [comment]
Thiếu 2 món bàn chà, bù hàng toa sau không tính tiền

**Comment by phanhoa155** [comment]
đã bù hàng
