### ISSUE TITLE
[Report bug] Tool Tool_CONGNOKH_INPUT

### ISSUE THREAD

**Issue by phatls** [phatls/CallCenter_Customer#55]
Địa chỉ tool:
DOSAT\IN_CM\1.RELEASE\Tool\Tool_CONGNOKH_INPUT\20170421_1

Có các lỗi sau:

**Comment by phatls** [comment]
# 1. Load file mẫu thanh toán ko chạy được
Điều kiện cần:
Cấu hình đầu đủ file trong FCHECK

Tái hiện:
1. Mở sheet [DON HANG]
2. Chọn load
3. Chọn file sau:
DOSAT\EX_ACCOUNTIN_TO_SALES\1.RELEASE\LATEST_VERSION\TONG HOP PHIEU THU\BCTT_20170420.xlsx
Hoặc chọn
[BCTT_20170420.xlsx](https://github.com/phatls/CallCenter_Customer/files/946725/BCTT_20170420.xlsx)

Kết quả hiện tại:
![image](https://cloud.githubusercontent.com/assets/5689342/25273510/3af7be9e-26b6-11e7-8cea-8b9fa659bd35.png)

Kết quả mong đợi:
Load đúng vào như thứ tự input

Ghi chú: 
Các file khác ở tại:
DOSAT\EX_ACCOUNTIN_TO_SALES\1.RELEASE\LATEST_VERSION\TONG HOP PHIEU THU
BCTT_20170417.xlsx
BCTT_20170418.xlsx
BCTT_20170419.xlsx

Ko bị lỗi

**Comment by phatls** [comment]
# 2. Tính năng UPD.NO
Hỏi: Hãy cho ví dụ điền các trường 
![image](https://cloud.githubusercontent.com/assets/5689342/25273570/8e228766-26b6-11e7-95cc-61debc800a73.png)
Khi sử dung tính năng này

**Comment by phatls** [comment]
# 3. Không load được TONG HOP công nợ
Điều kiện cần:
Cấu hình đầu đủ file trong FCHECK
File công nợ cá nhân
[CONGNOKH_HOAPTA.xlsx](https://github.com/phatls/CallCenter_Customer/files/946761/CONGNOKH_HOAPTA.xlsx)

Tái hiện:
1. Vào [TONG HOP] 
2. Chọn Update

Kết quả thực tế: Ko thấy hiện công nợ gì
Kết quả mong đợi: Hiển thị công nợ như phiên bản trước

**Comment by luantm** [comment]
hi a Phát,
(1) -> cần chuẩn hóa lại tên KH ->đã nhờ Hoa với Trinh cập nhật lại DSKH bị lỗi khai báo format(ds kèm theo)
(2) ->![image](https://cloud.githubusercontent.com/assets/18589252/25300905/63b8d708-2744-11e7-9c7c-f34edc872001.png)
-> Khi số nợ cũ hiện ra không đúng -> nhập lại số mới -> UPD.NO -> Load lại cửa hàng thì sẽ ra số vừa cập nhật.
3.Dữ liệu lấy từ: DOSAT\EX_SALES_TO_ACCOUNTIN\1.RELEASE\LATEST_VERSION\TONGCONGNOKH
-> check lại file dữ liệu.
Thanks
Luân Trần
