### ISSUE TITLE
[Weekly report][HoaPTA] Từ 02/5/2017 đến 06/5/2017

### ISSUE THREAD

**Issue by phanhoa155** [phatls/CallCenter_Customer#70]
02/5/2017 (tiếp tục #56)
Theo quy định về công việc tại:
#28

1. Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)

- Done

- Chưa xong
#57
#35
#40
#51

2. Nhận đơn hàng (10h ~ 12h, 13h ~ 16h30)

3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)

4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)

- Mới:
https://github.com/phatls/CallCenter_Customer/issues/71
- Chưa xong:
#57
#35
#40
#51
#69
- Bù hàng:
#62
#68

**Comment by phanhoa155** [comment]
03/5/2017 (tiếp tục #56)
Theo quy định về công việc tại:


1. Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)
- Done


- Chưa xong
#57
#35
#40
#51
#69


2. Nhận đơn hàng (10h ~ 12h, 13h ~ 16h30)

[BCVT_20170503.xlsx](https://github.com/phatls/CallCenter_Customer/files/975233/BCVT_20170503.xlsx)

3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)

4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)

- Mới:

https://github.com/phatls/CallCenter_Customer/issues/72
- Chưa xong:
#57
#35
#40
#51
#69

- Bù hàng:
#62
#68

**Comment by phanhoa155** [comment]
04/5/2017 (tiếp tục #56)
Theo quy định về công việc tại:
#28

1. Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)
- Done
#68
- Chưa xong
#57
#35
#40
#51
#69

2. Nhận đơn hàng (10h ~ 12h, 13h ~ 16h30)

3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)

4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)

- Mới:

- Chưa xong:
#57
#35
#40
#51
#69

- Bù hàng:
#62

**Comment by phanhoa155** [comment]
05/5/2017 (tiếp tục #56)
Theo quy định về công việc tại:
#28

1. Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)
- Done
#51

- Chưa xong

#57
#35
#40
#69

2. Nhận đơn hàng (10h ~ 12h, 13h ~ 16h30)

3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)

4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)

- Mới:


- Chưa xong:
#57
#35
#40
#69


- Bù hàng:
#62

**Comment by phanhoa155** [comment]
06/5/2017 
Theo quy định về công việc tại:
#28

1.Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)
- Done


- Chưa xong

#57
#35
#40
#69

2. Nhận đơn hàng (10h ~ 12h, 13h ~ 16h30)


3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)

4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)

- Mới:

https://github.com/phatls/CallCenter_Customer/issues/73
- Chưa xong:

#57
#35
#40
#69
- Bù hàng:
#62

**Comment by phanhoa155** [comment]
Tổng kết Từ 2/5/2017 đến 6/5/2017

Theo quy định về công việc tại:
https://github.com/phatls/CallCenter_Customer/issues/28

1. Xử lý các issue cũ, cập nhật tiến độ các issue (8h~10h)
Done
#51
#68
2. Đơn hàng nhận được:
[BCVT_20170506.xlsx](https://github.com/phatls/CallCenter_Customer/files/982462/BCVT_20170506.xlsx)

![image](https://cloud.githubusercontent.com/assets/5689342/25791788/eccc85e4-33ec-11e7-9752-83290f72fab5.png)

![image](https://cloud.githubusercontent.com/assets/5689342/25792381/77ba8ad6-33f0-11e7-9414-fb511a97c141.png)


3. Ghi nhận/thông báo issue (10h ~ 12h, 13h ~ 16h30)
4. Xem xét và ghi nhận issue phát sinh trong ngày chuẩn bị ngày làm việc kế tiếp (16h30 ~ 17h)
- Chưa xử lý:
#62 
#57
#35
#40
#69
#73
- Cần thỏa luận:
#40
- Vớt toa hàng:

**Comment by phatls** [comment]
08/5/2017
Tiếp tục tại:
#75
